ARM: 7272/1: S3C24XX: Fix build error for missing <mach/system-reset.h>
Since the arch/arm/mach-s3c2410/include/mach/system-reset.h has
been removed by commit 42abea6b ("ARM: restart: remove the now
empty arch_reset()"), so the inclusion of <mach/system-reset.h>
should be removed at the plat-s3c24xx/cpu.c file.

The build error happens like following:
  arch/arm/plat-s3c24xx/cpu.c:41: fatal error: mach/system-reset.h: No such file or directory

Signed-off-by: Kukjin Kim <kgene.kim@samsung.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>