ARM: sunxi: fix struct sys_timer removal
Commit a6b7089 "ARM: delete struct sys_timer" removed struct sys_timer,
but didn't update mach-sunxi/sunxi.c for this change, even though the
sunxi timer implementation itself was updated. This caused a build break:

arch/arm/mach-sunxi/sunxi.c:94:2: error: unknown field 'timer' specified in initializer
arch/arm/mach-sunxi/sunxi.c:94:12: error: 'sunxi_timer' undeclared here (not in a function)

Signed-off-by: Stephen Warren <swarren@nvidia.com>
Signed-off-by: Olof Johansson <olof@lixom.net>