tty/amiserial: Add missing argument for tty_unlock()
commit e06c98c775b9e456881c585147b4e8a8d01be2e0 ("tty_lock: Localise the lock")
missed that cdede5aae11be7be84a07a8338c907333800c7ef ("drivers/tty/amiserial.c:
add missing tty_unlock") just added a new caller of tty_unlock():

drivers/tty/amiserial.c: In function ‘set_serial_info’:
drivers/tty/amiserial.c:1077: error: too few arguments to function ‘tty_unlock’

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>