HID: select NEW_LEDS for driver of Lenovo ThinkPad USB Keyboard with TrackPoint
commit 'HID: Driver for Lenovo Keyboard with Trackpoint'
(d7586405b098f2f891d166a3b510c13a00ab58a4) introduced a compiling error due to
unmetting dependency of CONFIG_LEDS_CLASS.

on i386:

ERROR: "led_brightness_set" [drivers/leds/led-class.ko] undefined!
ERROR: "leds_list" [drivers/leds/led-class.ko] undefined!
ERROR: "leds_list_lock" [drivers/leds/led-class.ko] undefined!

Reported-by: Randy Dunlap <rdunlap@xenotime.net>
Signed-off-by: Bryan Wu <bryan.wu@canonical.com>
Signed-off-by: Jiri Kosina <jkosina@suse.cz>