ASoC: Fix build error in twl4030.c
Fix the (likely cut-n-paste) error by commit
64953fc91113daa0c04a0a6a7dbf36d84e6c918b, which causes the error below:
  sound/soc/codecs/twl4030.c: In function 'twl4030_read_reg_cache':
  sound/soc/codecs/twl4030.c:152: error: 'cache' undeclared (first use in this function)

Signed-off-by: Takashi Iwai <tiwai@suse.de>