ARM: EXYNOS: Fix compilation error with mach-exynos4-dt board
Commit 648ac90 ("ARM: EXYNOS: add support uart for EXYNOS4 and
EXYNOS5") renames S5P_PA_UARTn to EXYNOS4_PA_UARTn. Hence we
need to do similar modification in mach-exynos4-dt.c to fix
compilation error.

arch/arm/mach-exynos/mach-exynos4-dt.c:40:2: error: 'S5P_PA_UART0'
undeclared here (not in a function)

Signed-off-by: Tushar Behera <tushar.behera@linaro.org>
Signed-off-by: Kukjin Kim <kgene.kim@samsung.com>