drivers/of: fix build error when CONFIG_PPC_DCR is set
Commit ffa6f5f3b754e3746289bd4db5e7584f0c495363 (of:
Merge of_device_alloc() and of_device_make_bus_id()) moved code that
does calls a dcr routine without including the correct header which
causes the following build error on some powerpc configurations:

drivers/of/platform.c: In function 'of_device_make_bus_id':
drivers/of/platform.c:437: error: implicit declaration of function 'of_translate_dcr_address'

This patch adds the appropriate header to drivers/of/platform.c

Signed-off-by: Grant Likely <grant.likely@secretlab.ca>